### ISSUE TITLE
my silly idea for your great ac

### ISSUE THREAD

**Issue by kanture** [Scythe-Anticheat/Scythe-AntiCheat#126]
Maybe add a whitelist feature for players that are allowed to hack? may not seem logical but alot of other anticheats dont have it,

it would be nice to add,

**Comment by MrDiamond64** [comment]
The reason that there is no whitelist feature is because hackers may be able to add themselves to the whitelist and be able to bypass the entire anticheat. However in the [config.js](https://github.com/Scythe-Anticheat/Scythe-AntiCheat/blob/main/scripts/data/config.js#L15) file there is an option called `disableFlagsFromScytheOp` which can allow anyone with the `op` tag to not get flagged by the anticheat. You can enable that instead.

**Comment by kanture** [comment]
> The reason that there is no whitelist feature is because hackers may be able to add themselves to the whitelist and be able to bypass the entire anticheat. However in the [config.js](https://github.com/Scythe-Anticheat/Scythe-AntiCheat/blob/main/scripts/data/config.js#L15) file there is an option called `disableFlagsFromScytheOp` which can allow anyone with the `op` tag to not get flagged by the anticheat. You can enable that instead.

Is there a java version for scythe anticheat tho?

**Comment by MrDiamond64** [comment]
> Is there a java version for scythe anticheat tho?

No.
